import {createScore} from './audio.js';
import {GAME_SOUNDTRACK,GAME_PLAYLISTS} from './game-soundtrack.js';
import {logoFilmMarkup,LOGO_FILM_DURATION} from './logo-film.js';
import {bindMenuVideo} from './menu-video.js';
import {projectTurnBlocks,detectEvents} from './presentation.js';
const KEY='luoxian_beta3_settings';
const defaults={master:75,music:60,sfx:65,muteBackground:true,quality:'high',motion:true,scale:100,brightness:100,textSpeed:38,requestInterval:8,mode:'windowed',resolution:'1600x900',intro:true};
export function createExperience({aiClient,onAiSettings,onTitle,onExport,onImport,onReady=async()=>{}}){
 let settings={...defaults};try{settings={...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')};}catch{}
 const audio=createScore(()=>settings,{tracks:GAME_SOUNDTRACK,playlists:GAME_PLAYLISTS,initialScene:'intro',smoothManual:true});let writing=false,transitioning=false,skip=false,lastFocus=null,events=[],eventShowing=false;
 const el=(id)=>document.getElementById(id);
 const root=document.createElement('div');root.id='beta3Experience';root.innerHTML=`
 <section id="cinematic" class="cinematic" aria-label="落仙开场">
  ${logoFilmMarkup()}
  <button id="skipIntro" class="subtle-button">跳过开场 <kbd>Esc</kbd></button><button id="introSound" class="subtle-button">开启声音</button>
 </section>
 <div id="settingsLayer" class="b3-layer" hidden><section class="b3-dialog settings-dialog" role="dialog" aria-modal="true" aria-labelledby="settingsTitle">
  <header><div><small>PREFERENCES · 随心而定</small><h2 id="settingsTitle">天地设定</h2></div><button data-close="settingsLayer" aria-label="关闭设置">×</button></header>
  <div class="settings-layout"><nav class="settings-nav" aria-label="设置分类">
   <button data-setting-tab="sound" class="selected">音律 <small>AUDIO</small></button><button data-setting-tab="video">画境 <small>DISPLAY</small></button><button data-setting-tab="play">叙事 <small>GAMEPLAY</small></button><button data-setting-tab="ai">灵机 <small>AI CONNECTION</small></button><button data-setting-tab="access">辅助 <small>ACCESSIBILITY</small></button>
  </nav><div class="settings-pages">
  <section data-settings-page="sound"><h3>山河有声</h3><p>四首落仙配乐。开场与封面：若还能见你 → 打斗版 → 音乐版；进入此世：loop版 → 音乐版 → 打斗版，循环播放，曲间柔和衔接。</p>
   ${slider('master','总音量',0,100)}${slider('music','背景音乐',0,100)}${slider('sfx','交互音效',0,100)}${check('muteBackground','后台静音','切到其他窗口时暂停音频。')}
   <div class="music-card"><span class="track-disc" aria-hidden="true">♫</span><div><b id="currentTrack">落仙配乐</b><small id="trackInfo">开场与旅程 · 顺序播放</small></div><button id="musicPlayback">播放音乐</button><button id="nextMusic">下一首 ↠</button></div><button id="testSound">试听 · 玉磬</button>
  </section>
  <section data-settings-page="video" hidden><h3>万象画境</h3><p>窗口模式、尺寸与画面效果。</p>
   ${select('mode','显示模式',[['windowed','窗口化'],['borderless','无边框全屏'],['fullscreen','全屏']])}
   ${select('resolution','窗口分辨率',[['1280x720','1280 × 720'],['1600x900','1600 × 900'],['1920x1080','1920 × 1080'],['2560x1440','2560 × 1440']])}
   <p class="field-note">全屏使用屏幕原生尺寸；窗口分辨率在窗口化模式生效。F11 / Alt+Enter 切换全屏。</p>
   ${select('quality','特效质量',[['high','精致 · 云雾 / 光晕 / 粒子'],['medium','均衡 · 减少粒子'],['low','轻量 · 静态背景']])}${slider('brightness','画面亮度',75,125)}
   <button id="applyDisplay">应用显示设置</button><p id="displayFeedback" role="status"></p>
  </section>
  <section data-settings-page="play" hidden><h3>一字一山河</h3><p>对白与剧情按发生顺序连续呈现，阅读中可随时展开全文。</p>
   ${slider('textSpeed','字幕间隔 · 毫秒 / 字',0,100)}${slider('requestInterval','AI 请求最小间隔 · 秒',3,30)}
   <p class="field-note">减慢字幕不等于避免限流。请求统一控制间隔，不会将重复点击排队，遇到限流遵守服务端冷却时间，不自动切换模型。</p><button id="replayIntro">重看开场</button><button id="exportJourney">导出命簿</button><button id="importJourney">导入命簿</button><input type="file" id="journeyFile" accept=".json" hidden><p id="journeyFeedback" role="status"></p>
  </section>
  <section data-settings-page="ai" hidden><h3>接续此世</h3><p>可使用本机 Qwen 进行叙事；云端 AI 为可选辅助。世界状态始终由命簿保存。</p><div class="connection-card"><i></i><div><b id="b3Provider">正在读取连接…</b><p id="b3KeyState"></p></div></div><button id="configureAi" class="gold-button">配置本地或云端 AI ↗</button><p class="field-note">云端 Key 由本机 Windows 用户加密保存，不写入游戏存档或发行包。</p></section>
  <section data-settings-page="access" hidden><h3>舒适阅读</h3>${slider('scale','界面字号 · %',100,140)}${check('motion','动态效果','关闭后减少位移、粒子和闪光。也尊重系统减少动态设置。')}<dl class="key-guide"><dt>Enter</dt><dd>提交对白</dd><dt>Shift + Enter</dt><dd>输入换行</dd><dt>Esc</dt><dd>关闭弹窗 / 打开设置</dd><dt>F11</dt><dd>切换全屏</dd></dl></section>
  </div></div><footer><span id="settingsSaved">设置会自动保存在本机</span><button id="resetSettings">恢复默认</button><button data-close="settingsLayer" class="gold-button">完成</button></footer>
 </section></div>
 <div id="keyGate" class="b3-layer" hidden><section class="b3-dialog compact-dialog" role="dialog" aria-modal="true" aria-labelledby="keyGateTitle"><div class="dialog-emblem">灵</div><small>AI CONNECTION REQUIRED</small><h2 id="keyGateTitle">此世尚未接续</h2><p>请确认所选本地模型已就绪，或为云端模式配置 API Key。</p><p id="keyGateReason"></p><footer><button data-close="keyGate">返回</button><button id="gateSettings" class="gold-button">前往设置</button></footer></section></div>
 <div id="eventLayer" class="b3-layer event-layer" hidden><section class="event-card" role="dialog" aria-modal="true" aria-labelledby="eventTitle"><div class="event-orbit"></div><div id="eventRune" class="event-rune">境</div><small id="eventKicker">FATE UNFOLDS</small><h2 id="eventTitle"></h2><p id="eventText"></p><button id="eventContinue" class="gold-button">继续此世</button></section></div>
 <div id="newConfirm" class="b3-layer" hidden><section class="b3-dialog compact-dialog" role="dialog" aria-modal="true" aria-labelledby="newConfirmTitle"><small>A NEW CHAPTER</small><h2 id="newConfirmTitle">另启一世</h2><p>新的旅程将替换当前自动存档。旧旅程的对白记录仍会保留；建议先在命簿中导出存档备份。</p><footer><button data-close="newConfirm">返回</button><button id="confirmNew" class="gold-button">确认启程</button></footer></section></div>
 `;document.body.append(root);const now=document.createElement('div');now.className='now-playing';now.innerHTML='<span aria-hidden="true">♫</span><span id="coverTrack">山海乐章 · 点击开启声音</span><button id="coverNext" aria-label="播放下一首" title="下一首">↠</button>';document.body.append(now);
 function slider(id,label,min,max){return `<label class="setting-row"><span>${label}</span><div><input type="range" data-pref="${id}" min="${min}" max="${max}"><output data-output="${id}"></output></div></label>`;}
 function check(id,label,note){return `<label class="setting-row switch-row"><span>${label}<small>${note}</small></span><input type="checkbox" data-pref="${id}"></label>`;}
 function select(id,label,opts){return `<label class="setting-row"><span>${label}</span><select data-pref="${id}">${opts.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label>`;}
 function reduced(){return !settings.motion||matchMedia('(prefers-reduced-motion: reduce)').matches;}
 function apply(){document.documentElement.classList.toggle('low-spec-ui',settings.quality==='low');document.documentElement.dataset.quality=settings.quality;document.documentElement.classList.toggle('reduced-motion',reduced());document.documentElement.style.setProperty('--reading-scale',settings.scale/100);document.documentElement.style.setProperty('--ui-scale',settings.scale/100);document.documentElement.style.setProperty('--scene-brightness',settings.brightness/100);audio.apply();}
 function sync(){el('applyDisplay').disabled=false;root.querySelectorAll('[data-pref]').forEach(input=>{const k=input.dataset.pref;if(input.type==='checkbox')input.checked=settings[k];else input.value=settings[k];const out=root.querySelector(`[data-output="${k}"]`);if(out)out.value=settings[k];});}
 function save(){localStorage.setItem(KEY,JSON.stringify(settings));apply();el('settingsSaved').textContent='已保存 · 仅显示模式需点击应用';}
 root.querySelectorAll('[data-pref]').forEach(input=>input.addEventListener('input',()=>{const k=input.dataset.pref;settings[k]=input.type==='checkbox'?input.checked:input.type==='range'?Number(input.value):input.value;sync();if(['master','music','sfx'].includes(k)){audio.setEnabled(true);audio.unlock();syncAudio();}save();}));
 function open(id){lastFocus=document.activeElement;el(id).hidden=false;el(id).querySelector('button,input,select')?.focus();audio.sfx('click');}
 let newResolution=null;
 function close(id){const layer=el(id);if(layer.hidden)return;layer.hidden=true;lastFocus?.focus();if(id==='newConfirm'&&newResolution){newResolution(false);newResolution=null;}}
 root.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));
 root.querySelectorAll('.b3-layer').forEach(layer=>layer.addEventListener('click',e=>{if(e.target===layer&&!['eventLayer','newConfirm'].includes(layer.id))close(layer.id);}));
 function tab(name){root.querySelectorAll('[data-settings-page]').forEach(p=>p.hidden=p.dataset.settingsPage!==name);root.querySelectorAll('[data-setting-tab]').forEach(b=>b.classList.toggle('selected',b.dataset.settingTab===name));}
 root.querySelectorAll('[data-setting-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.settingTab));
 async function openSettings(name='sound'){sync();tab(name);open('settingsLayer');syncAudio();trackUpdate(audio.getNowPlaying?.());if(window.lxNative)window.nativeAction('window-status').then(displayResult).catch(()=>{});const s=aiClient.loadSettings();el('b3Provider').textContent=`${s.mode} · ${s.models?.[s.mode]||'尚未选择模型'}`;el('b3KeyState').textContent='正在检查凭据…';const st=await aiClient.status(true);el('b3KeyState').textContent=st.cloud?.configured?.[s.mode]?'API Key 已保存；可在配置中测试连接。':'尚未设置有效的云端 API Key。';}
 el('configureAi').onclick=()=>{close('settingsLayer');onAiSettings();};el('gateSettings').onclick=()=>{close('keyGate');openSettings('ai');};el('testSound').onclick=async()=>{audio.setEnabled(true);await audio.unlock();audio.sfx('realm');syncAudio();};
 function syncAudio(){const on=audio.isEnabled();el('musicPlayback').textContent=on?'暂停音乐与音效':'播放音乐';const b=el('audioButton');if(b){b.classList.toggle('muted',!on);b.querySelector('span').textContent=on?'音':'静';}}
 function trackUpdate(t){if(!t)return;el('currentTrack').textContent=t.title;el('trackInfo').textContent=`${['game','danger'].includes(t.scene)?'旅程循环':'开场与封面'} · ${t.index} / ${t.total} · 顺序播放`;el('coverTrack').textContent=t.title;syncAudio();}
 audio.subscribe?.(trackUpdate);el('musicPlayback').onclick=async()=>{audio.setEnabled(!audio.isEnabled());await audio.unlock();syncAudio();};const nextMusic=async()=>{audio.setEnabled(true);await audio.unlock();await audio.nextTrack?.();syncAudio();};el('nextMusic').onclick=nextMusic;el('coverNext').onclick=nextMusic;

 function displayResult(result){if(!result?.width)return;const mode={windowed:'窗口化',borderless:'无边框全屏',fullscreen:'全屏'}[result.mode]||result.mode;el('displayFeedback').textContent=`当前：${mode} · ${result.width} × ${result.height} 逻辑像素${result.scaleFactor?' · 系统缩放 '+Math.round(result.scaleFactor*100)+'%':''}${result.clamped?'。所选尺寸超出屏幕，已适配可用区域。':''}`;}
 async function applyDisplay(){const [width,height]=settings.resolution.split('x').map(Number);const button=el('applyDisplay');button.disabled=true;el('displayFeedback').textContent='正在应用…';try{if(window.lxNative){const result=await window.nativeAction('window-settings',{mode:settings.mode,width,height});displayResult(result);if(!result?.width)el('displayFeedback').textContent='显示请求已发送。';}else if(settings.mode==='windowed'){if(document.fullscreenElement)await document.exitFullscreen();el('displayFeedback').textContent='当前为浏览器预览，精确窗口尺寸请通过 LuoXian.exe 应用。';}else{await document.documentElement.requestFullscreen();el('displayFeedback').textContent='已进入浏览器全屏。';}}catch(error){el('displayFeedback').textContent='应用失败：'+error.message;}finally{button.disabled=false;}}
 window.addEventListener('lx:display-changed',e=>{displayResult(e.detail);if(e.detail?.mode&&e.detail.mode!==settings.mode){settings.mode=e.detail.mode;sync();save();}});
 el('applyDisplay').onclick=applyDisplay;el('resetSettings').onclick=async()=>{settings={...defaults};sync();audio.setEnabled(true);save();syncAudio();await applyDisplay();};
 el('exportJourney').onclick=async()=>{try{await onExport?.();el('journeyFeedback').textContent='命簿已导出。请保管好你的旅程文件。';}catch(error){el('journeyFeedback').textContent=error.message;}};
 el('importJourney').onclick=()=>el('journeyFile').click();
 el('journeyFile').onchange=async()=>{const file=el('journeyFile').files[0];if(!file)return;try{await onImport?.(file);el('journeyFeedback').textContent='命簿已导入，当前旅程已更新。';}catch(error){el('journeyFeedback').textContent='导入失败：'+error.message;}finally{el('journeyFile').value='';}};
 async function requireKey(){const s=aiClient.loadSettings();let info;try{info=await aiClient.status(true);}catch{}const local=['local','hybrid-assist'].includes(s.mode);const ok=local?Boolean(info?.local?.runtimeInstalled&&info?.local?.modelInstalled):Boolean(info?.cloud?.configured?.[s.mode]&&s.models?.[s.mode]);if(!ok){el('keyGateReason').textContent=local?'本地 Qwen 尚未就绪；请检查模型安装状态，或主动切换到已配置的云端模式。':'请选择模型，并确认已为当前云端供应商保存 Key。';open('keyGate');}return ok;}
 let introTimer,finishing=false,ready=false;
 document.body.classList.add('video-era');
 const coverVideo=el('menuLoopVideo');
 bindMenuVideo(coverVideo,el('titleScreen'));
 const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
 function menu(){const title=el('titleScreen');if(!title)return;title.querySelectorAll('.journey-button').forEach((b,i)=>b.style.setProperty('--menu-index',i));title.classList.remove('menu-ready');void title.offsetWidth;title.classList.add('menu-ready');}
 async function finishIntro(){if(!ready||finishing)return;finishing=true;clearTimeout(introTimer);el('cinematic').classList.add('departing');audio.setScene(el('gameShell')&&!el('gameShell').hidden?'game':'title');coverVideo?.play().catch(()=>el('titleScreen')?.classList.add('video-failed'));await delay(reduced()?150:850);el('cinematic').hidden=true;menu();finishing=false;el('continueJourneyButton')?.hidden?el('newJourneyButton')?.focus():el('continueJourneyButton')?.focus();}
 function intro(){if(!ready||finishing)return;clearTimeout(introTimer);close('settingsLayer');const c=el('cinematic');c.hidden=false;c.classList.remove('playing','departing');el('titleScreen')?.classList.remove('menu-ready');void c.offsetWidth;c.classList.add('playing');audio.setScene('intro');audio.unlock();introTimer=setTimeout(finishIntro,reduced()?1600:LOGO_FILM_DURATION);}
 async function boot(){const veil=el('bootVeil');try{ready=false;void audio.unlock();if(veil){veil.hidden=false;veil.classList.remove('leaving');el('bootRetry').hidden=true;el('bootStatus').textContent='正在载入山河与命簿…';}await Promise.all([onReady(),document.fonts.ready,...['tianque-sword.png','rain-awakening.png'].map(name=>new Promise((resolve,reject)=>{const img=new Image();img.onload=resolve;img.onerror=()=>reject(new Error('美术资源载入失败'));img.src=new URL('../assets/'+name,import.meta.url).href;})),fetch('/api/status').then(async r=>{if(!r.ok)throw Error('游戏引擎未就绪');const status=await r.json();if(status.healthy===false)throw Error('游戏文件不完整，请先修复游戏');}),delay(1100)]);ready=true;document.body.classList.remove('booting');if(veil){veil.classList.add('leaving');await delay(600);veil.hidden=true;}intro();if(new URLSearchParams(location.search).has('settings')){await finishIntro();openSettings('ai');}}catch(error){if(veil){el('bootStatus').textContent='载入未完成：'+error.message;el('bootRetry').hidden=false;el('bootRetry').onclick=boot;}}}
 async function enter(reveal){transitioning=true;try{const veil=el('entryVeil');veil?.classList.add('covered');await delay(reduced()?100:550);reveal();audio.setScene('game');const game=el('gameShell');game?.classList.remove('entering');void game?.offsetWidth;game?.classList.add('entering');veil?.classList.remove('covered');await delay(reduced()?100:1650);game?.classList.remove('entering');}finally{transitioning=false;}}
 el('skipIntro').onclick=finishIntro;el('introSound').onclick=async()=>{await audio.unlock();el('introSound').textContent='声音已开启';};el('replayIntro').onclick=intro;
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!el('cinematic').hidden){finishIntro();return;}const layer=[...root.querySelectorAll('.b3-layer')].reverse().find(l=>!l.hidden);if(layer){if(layer.id==='eventLayer')nextEvent();else close(layer.id);}else if(!document.querySelector('.ai-config-layer:not([hidden]),.law-layer:not([hidden]),.world-drawer:not([hidden])'))openSettings();}if(e.key==='Tab'){const layer=[...root.querySelectorAll('.b3-layer')].reverse().find(l=>!l.hidden);if(!layer)return;const focusable=[...layer.querySelectorAll('button,input,select')].filter(x=>!x.disabled&&x.getClientRects().length);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 let lastHover=0;document.addEventListener('pointerover',e=>{if(e.target.closest('button')&&Date.now()-lastHover>100){audio.sfx('hover');lastHover=Date.now();}});document.addEventListener('click',e=>{if(e.target.closest('button'))audio.sfx('click');});
 async function reveal(node,text,target){if(!settings.textSpeed||reduced()||skip){node.textContent=text;if(target)target.scrollTop=target.scrollHeight;return;}const chars=Array.from(text);let start=performance.now();await new Promise(resolve=>{function frame(now){const n=skip?chars.length:Math.floor((now-start)/settings.textSpeed)+1;node.textContent=chars.slice(0,n).join('');if(target)target.scrollTop=target.scrollHeight;if(n>=chars.length)resolve();else requestAnimationFrame(frame);}requestAnimationFrame(frame);});}
 const readStatus=el('readingStatus');el('skipText').onclick=()=>{skip=true;};
 async function renderBlocks(blocks,speech,{animate=true}={}){const rows=projectTurnBlocks(blocks,speech);writing=animate;skip=false;el('skipText').hidden=!animate;readStatus.textContent=animate?'墨迹渐显 · 正在展开此回合':'命簿已载入';
  for(const b of rows){const dialogue=b.type==='dlg';const target=el('storyScroll');const article=document.createElement('article');article.className=dialogue?`dialogue-line ${b.player?'is-player':''}`:`story-block ${b.type||'narr'}`;
   if (!animate) article.style.animation='none';
   if(dialogue){const name=document.createElement('b');name.textContent=b.name||'未识之人';const badge=document.createElement('small');badge.textContent=b.player?'此言由你':'山河回响';name.append(badge);article.append(name);}
   const p=document.createElement('p');article.append(p);target.append(article);if(animate){target.scrollTop=target.scrollHeight;await reveal(p,b.text,target);}else p.textContent=b.text;target.scrollTop=target.scrollHeight;
  }writing=false;el('skipText').hidden=true;readStatus.textContent='此回合已展开 · 静候你落笔';
 }
 function nextEvent(){close('eventLayer');eventShowing=false;const evt=events.shift();if(!evt)return;eventShowing=true;const layer=el('eventLayer');layer.dataset.kind=evt.kind;el('eventTitle').textContent=evt.title;el('eventText').textContent=evt.text;el('eventRune').textContent=({realm:'境',quest:'成',newquest:'契',failedquest:'断',item:'藏',revival:'生',danger:'劫',death:'寂',travel:'山',relationship:'缘',ending:'终'})[evt.kind];el('eventContinue').textContent=['death','ending'].includes(evt.kind)?'返回封面':'继续此世';el('eventContinue').onclick=()=>{if(['death','ending'].includes(evt.kind))onTitle();nextEvent();};audio.sfx(evt.kind);open('eventLayer');}
 function showEvents(before,after){events.push(...detectEvents(before,after));if(!eventShowing)nextEvent();}
 function confirmNew(){open('newConfirm');return new Promise(resolve=>{newResolution=resolve;el('confirmNew').onclick=()=>{newResolution=null;close('newConfirm');resolve(true);};});}
 let cooldownUntil=0;window.addEventListener('lx:cooldown',e=>{cooldownUntil=Date.now()+e.detail.ms;});setInterval(()=>{if(cooldownUntil>Date.now())readStatus.textContent=`灵机调息 · ${Math.ceil((cooldownUntil-Date.now())/1000)} 秒后可继续请求`;else if(cooldownUntil){cooldownUntil=0;readStatus.textContent='灵机已就绪';}},500);
 settings.scale=Math.max(100,Math.min(140,Number(settings.scale)||100));sync();apply();boot();if(window.lxNative)applyDisplay();
 function pendingSpeech(text){el('pendingSpeech')?.remove();if(!text)return;const row=document.createElement('article');row.id='pendingSpeech';row.className='dialogue-line is-player pending-speech';const name=document.createElement('b');name.textContent='顾长生 · 待世界回应';const p=document.createElement('p');p.textContent=text;row.append(name,p);el('storyScroll').append(row);el('storyScroll').scrollTop=el('storyScroll').scrollHeight;}
 return {audio,enter,menu,isTransitioning:()=>transitioning,openSettings,requireKey,renderBlocks,showEvents,confirmNew,pendingSpeech,isWriting:()=>writing,clear:()=>{el('pendingSpeech')?.remove();},skip:()=>{skip=true;}};
}
