export function createSaveUI({session,stateStore,getState,isBusy,requireKey,onLoad,onLeave,toast}){
 let busy=false,decision=null;const root=document.createElement('div');root.innerHTML=`
 <div id="saveLayer" class="b3-layer" hidden><section class="b3-dialog save-dialog" role="dialog" aria-modal="true" aria-labelledby="saveTitle"><header><div><small>CHRONICLES</small><h2 id="saveTitle">命簿 · 存档与读取</h2></div><button id="closeSaves" aria-label="关闭命簿">×</button></header><div id="saveSlots" class="save-slots"></div><p class="save-note">三个手动命簿独立保留。自动命簿每完成三个世界回合更新；读取任意命簿后，会以所读进度替换自动命簿。系统闲聊和背包操作不计入三个回合。</p><p id="saveFeedback" class="save-note save-error" role="status"></p></section></div>
 <div id="exitSaveLayer" class="b3-layer" hidden><section class="b3-dialog exit-save-dialog" role="dialog" aria-modal="true" aria-labelledby="exitSaveTitle"><small>THIS JOURNEY REMAINS</small><h2 id="exitSaveTitle">保存此刻的山河？</h2><p id="exitSaveText"></p><p id="exitSaveError" class="save-error" role="status"></p><div class="exit-choices"><button id="exitCancel">取消</button><button id="exitDiscard">不保存</button><button id="exitSave" class="gold-button">保存并退出</button></div></section></div>`;document.body.append(root);
 const el=id=>document.getElementById(id);const title=id=>id?'手动命簿 '+id.slice(-1):'自动命簿';
 function usable(){if(busy||isBusy()){toast('正在落笔或保存，请稍候');return false;}return true;}
 function close(){if(!busy){el('saveLayer').hidden=true;el('saveButton')?.focus();}}
 function render(){const info=session.info(),current=getState();el('saveSlots').replaceChildren();for(const id of [null,'slot1','slot2','slot3']){const saved=id?stateStore.loadSlot('ai',id):info.checkpoint?.state;const row=document.createElement('article');row.className='save-row';row.dataset.current=String(info.activeSlot===id&&!!current);const content=document.createElement('div'),h=document.createElement('h3'),p=document.createElement('p');h.textContent=title(id)+(info.activeSlot===id&&current?' · 当前':'');p.textContent=saved?`${saved.player.name} · 第 ${saved.story.day} 日 · ${saved.story.location} · ${new Date(saved.updatedAt).toLocaleString()}`:'尚未落笔';content.append(h,p);const controls=document.createElement('div');controls.className='save-controls';if(id){const save=document.createElement('button');save.textContent='保存';save.disabled=!current;save.onclick=async()=>{if(!usable())return;if(saved&&!(await choose('覆盖这份命簿？',`${title(id)} 的旧进度将由当前进度替换。`,true)))return;await run(async()=>{await session.save(getState(),id);toast('已保存至'+title(id));render();});};controls.append(save);}const load=document.createElement('button');load.textContent='读取';load.disabled=!saved;load.onclick=async()=>{if(!usable()||!(await requireKey()))return;if(getState()&&!(await choose('读取这份命簿？','当前未保存进度将被替换，自动命簿也会更新为所读进度。',true)))return;await run(async()=>{const next=await session.load(id);await onLoad(next);el('saveLayer').hidden=true;toast('已读取'+title(id));});};controls.append(load);row.append(content,controls);el('saveSlots').append(row);}}
 async function run(task){busy=true;root.querySelectorAll('button').forEach(b=>b.disabled=true);try{await task();}catch(e){el('saveFeedback').textContent=e.message;toast('操作未完成：'+e.message);}finally{busy=false;root.querySelectorAll('button').forEach(b=>b.disabled=false);if(!el('saveLayer').hidden)render();}}
 function choose(heading,text,confirmOnly=false){el('exitSaveTitle').textContent=heading;el('exitSaveText').textContent=text;el('exitSaveError').textContent='';el('exitDiscard').hidden=confirmOnly;el('exitSave').textContent=confirmOnly?'确认':'保存并退出';el('exitSaveLayer').hidden=false;el('exitCancel').focus();return new Promise(resolve=>{decision=resolve;});}
 function settle(value){if(busy||!decision)return;const resolve=decision;decision=null;el('exitSaveLayer').hidden=true;resolve(value);}
 el('exitCancel').onclick=()=>settle(null);el('exitDiscard').onclick=()=>settle(false);el('exitSave').onclick=()=>settle(true);el('closeSaves').onclick=close;
 root.addEventListener('click',e=>{if(e.target===el('saveLayer'))close();});
 document.addEventListener('keydown',e=>{if(el('saveLayer').hidden&&el('exitSaveLayer').hidden)return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(decision)settle(null);else close();}if(e.key==='Tab'){const layer=!el('exitSaveLayer').hidden?el('exitSaveLayer'):el('saveLayer');const buttons=[...layer.querySelectorAll('button')].filter(b=>!b.disabled&&b.getClientRects().length);if(!buttons.length)return;const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}},true);
 return {isBusy:()=>busy||!!decision,
  open(){if(!usable())return;el('saveFeedback').textContent='';render();el('saveLayer').hidden=false;el('closeSaves').focus();},
  async exit(target){if(!usable()||decision)return;const state=getState();if(state){const value=await choose('保存此刻的山河？',`保存会写入${title(session.info().activeSlot)}。不保存则保留最近一次命簿，之后的未保存进度会舍弃。`);if(value===null)return;busy=true;try{if(value)await session.save(state);}catch(e){toast('保存失败，尚未退出：'+e.message);return;}finally{busy=false;}}await onLeave(target);}
 };
}
